package org.utn.ba.tptacsg2.enums;

public enum TipoEstadistica {
    CANTIDAD_EVENTOS,
    CANTIDAD_EVENTOS_ACTIVOS,
    CANTIDAD_INSCRIPCIONES_TOTALES,
    CANTIDAD_INSCRIPCIONES_CONFIRMADAS,
    CANTIDAD_INSCRIPCIONES_WAITLIST,
    TASA_CONVERSION_WAITLIST,
    EVENTO_MAS_POPULAR,
    PROMEDIO_INSCRIPCIONES_POR_EVENTO
}